const r = require('express').Router();
const c = require('../controllers/viajeController');
const { auth, authorize } = require('../middleware/auth');
r.get('/', auth, c.getAll);
r.get('/:id', auth, c.getOne);
r.post('/', auth, authorize('administrador','logistica','trafico'), c.create);
r.put('/:id', auth, authorize('administrador','logistica','trafico'), c.update);
r.patch('/:id/estado', auth, c.cambiarEstado);
r.post('/:id/eventos', auth, c.addEvento);
r.post('/:id/gastos', auth, c.addGasto);
module.exports = r;
